### ISSUE TITLE
OSError: PicamError_UnexpectedNullPointer in PI.Picam_GetParameters with linux SDK 5.13.3

### ISSUE THREAD

**Issue by ma-tri-x** [ScopeFoundry/HW_picam#3]
Hi! 
In my case with a PIXIS 100 and libpicam.so.5.13.3 on linux,
the parameters for the PIXIS cannot be retreaved. I put some printouts to determine the function throwing the picam error into picam.py:
```
    def get_param_names(self):
        
        param_array = ctypes.c_void_p()
        #param_array = ctypes.POINTER(picam_ctypes.PicamParameter)()
        pcount = picam_ctypes.piint()
        
        print("point 00")
        self._err(PI.Picam_GetParameters(self.camera_handle, byref(param_array), byref(pcount)))
        print("point 01")
        data_p = ctypes.cast(param_array, ctypes.POINTER(ctypes.c_int))
        a = np.fromiter(data_p, dtype=int, count=pcount.value)
        self._err(PI.Picam_DestroyParameters(param_array))
        print("point 02")
        #print 'get_params', a
        param_list = []
#and so on
```
which throws
```
INFO:PicamHW:Connecting to PICAM
point 00: <bound method PiCAM._err of <ScopeFoundryHW.picam.picam.PiCAM object at 0x7f9441ae4be0>>
picam connection failed!
disabling connection
CRITICAL:root:Unhandled exception:Traceback (most recent call last):
  File "/home/labuser/anaconda3/envs/scopefoundry/lib/python3.6/site-packages/ScopeFoundry/hardware.py", line 208, in enable_connection
    raise err
  File "/home/labuser/anaconda3/envs/scopefoundry/lib/python3.6/site-packages/ScopeFoundry/hardware.py", line 204, in enable_connection
    self.connect()
  File "/home/labuser/anaconda3/envs/scopefoundry/lib/python3.6/site-packages/ScopeFoundryHW/picam/picam_hw.py", line 56, in connect
    supported_pnames = self.cam.get_param_names()
  File "/home/labuser/anaconda3/envs/scopefoundry/lib/python3.6/site-packages/ScopeFoundryHW/picam/picam.py", line 183, in get_param_names
    self._err(PI.Picam_GetParameters(self.camera_handle, byref(param_array), byref(pcount)))
  File "/home/labuser/anaconda3/envs/scopefoundry/lib/python3.6/site-packages/ScopeFoundryHW/picam/picam.py", line 312, in _err
    raise IOError(err_str)
OSError: PicamError_UnexpectedNullPointer

INFO:PicamTestApp:on_close
INFO:PicamTestApp:disconnecting picam
(scopefoundry) labuser@farshchian ((HEAD detached at 684743c)):~/Spectrometer/HW_picam$
```

so the method **PI.Picam_GetParameters** returns an error, it seems. I don't have a clue of how to work with ctypes, please help!

**Comment by ma-tri-x** [comment]
Hi! Sorry, do you have an idea? We would be really happy if we could make our PIXIS work again.
